export FontPanel from './FontPanel'
export ColorPanel from './ColorPanel'
export LayoutPanel from './LayoutPanel'
export SectionPanel from './SectionPanel'
export ImagePanel from './ImagePanel'
export SectionTypePanel from './SectionTypePanel'
export ComponentPanel from './ComponentPanel'