export const LOAD_ENTRIES_SUCCESS = 'LOAD_ENTRIES_SUCCESS'
export const LOAD_USERS_SUCCESS = 'LOAD_USERS_SUCCESS'
export const SELECT_USER = 'SELECT_USER'
export const SELECT_DATA = 'SELECT_DATA'
export const SELECT_TYPE_AND_SYMBOLS = 'SELECT_TYPE_AND_SYMBOLS'
export const LOAD_INTERVENTIONS_SUCCESS = 'LOAD_INTERVENTIONS_SUCCESS'
export const SELECT_INTERVENTION = 'SELECT_INTERVENTION'
export const CONFIRM_CHART_SUCCESS = 'CONFIRM_CHART_SUCCESS'
export const EDIT_ENTRY_DATE_DATA = 'EDIT_ENTRY_DATE_DATA'
export const EDIT_ENTRY_VALUE_DATA = 'EDIT_ENTRY_VALUE_DATA'
export const SELECT_ENGINE_MODE = 'SELECT_ENGINE_MODE'
export const UPDATE_INTERVENTION = 'UPDATE_INTERVENTION'


// BUILDER ACTIONS
export const LOAD_REPORT_DATA_SUCCESS = 'LOAD_REPORT_DATA_SUCCESS'
export const SAVE_REPORT_SUCCESS = 'SAVE_REPORT_SUCCESS'
export const CREATE_REPORT_SUCCESS = 'CREATE_REPORT_SUCCESS'
export const ADD_SECTION = 'ADD_SECTION'