// COLOR
export const CHANGE_PRIMARY_COLOR = 'CHANGE_PRIMARY_COLOR'
export const CHANGE_SECONDARY_COLOR = 'CHANGE_SECONDARY_COLOR'
export const CHANGE_TERTIARY_COLOR = 'CHANGE_TERTIARY_COLOR'
export const CHANGE_QUATERNARY_COLOR = 'CHANGE_QUATERNARY_COLOR'
export const CHANGE_QUINARY_COLOR = 'CHANGE_QUINARY_COLOR'
export const CHANGE_COLOR = 'CHANGE_COLOR'

// FONT
export const CHANGE_PRIMARY_FONT = 'CHANGE_PRIMARY_FONT'
export const CHANGE_SECONDARY_FONT = 'CHANGE_SECONDARY_FONT'
export const CHANGE_TERTIARY_FONT = 'CHANGE_TERTIARY_FONT'
export const CHANGE_FONT = 'CHANGE_FONT'

// ZOOM
export const APPLY_ZOOM = 'APPLY_ZOOM'