// COLOR
export const CHANGE_PRIMARY_COLOR = 'CHANGE_PRIMARY_COLOR'
export const CHANGE_SECONDARY_COLOR = 'CHANGE_SECONDARY_COLOR'
export const CHANGE_TERTIARY_COLOR = 'CHANGE_TERTIARY_COLOR'
export const CHANGE_QUATERNARY_COLOR = 'CHANGE_QUATERNARY_COLOR'
export const CHANGE_QUINARY_COLOR = 'CHANGE_QUINARY_COLOR'
export const CHANGE_COLOR = 'CHANGE_COLOR'

// COMPONENT
export const LOAD_COMPONENTS = 'LOAD_COMPONENTS'
export const ADD_COMPONENT= 'ADD_COMPONENT'

// FONT
export const CHANGE_PRIMARY_FONT = 'CHANGE_PRIMARY_FONT'
export const CHANGE_SECONDARY_FONT = 'CHANGE_SECONDARY_FONT'
export const CHANGE_TERTIARY_FONT = 'CHANGE_TERTIARY_FONT'
export const CHANGE_FONT = 'CHANGE_FONT'

// META
export const CHANGE_SIZE = 'CHANGE_SIZE'
export const CHANGE_LAYOUT = 'CHANGE_LAYOUT'
export const SET_META_INFO = 'SET_META_INFO'

// SECTION
export const ADD_SECTION = 'ADD_SECTION'
export const LOAD_SECTIONS = 'LOAD_SECTIONS'
export const UPDATE_SECTION = 'UPDATE_SECTION'
export const ADD_MENU_ELEMENT = 'ADD_MENU_ELEMENT'
export const UPDATE_MENU_ELEMENT = 'UPDATE_MENU_ELEMENT'
export const DELETE_MENU_ELEMENT = 'DELETE_MENU_ELEMENT'

// SECTION type
export const ADD_SECTION_TYPE = 'ADD_SECTION_TYPE'

// STRUCTURE
export const ADD_SECTION_STRUCTURE = 'ADD_SECTION_STRUCTURE'


// STYLE
export const ADD_SECTION_STYLE = 'ADD_SECTION_STYLE'

// ZOOM
export const APPLY_ZOOM = 'APPLY_ZOOM'