export default {
  id: null,
  colors: {},
  components: [],
  fontFamilies: {},
  meta: {
    editor: true,
    name: '',
    orientation: '',
    layout: '',
    size: '',
    name: '',
  },  
  saving: false,
  section_types: [],
  sections: [],
  structure: [],
  styles: [],
  template: {},
  zoom: 100,
}
